### ISSUE TITLE
?? torrc_tmp: No such file or directory

### ISSUE THREAD

**Issue by sghtx** [jayfajardo/rasptor#1]
Configuring Tor..
./setup.sh: line 152: /etc/tor/torrc_tmp: No such file or directory
./setup.sh: line 153: /etc/tor/torrc_tmp: No such file or directory
./setup.sh: line 164: /etc/tor/torrc_tmp: No such file or directory
./setup.sh: line 165: /etc/tor/torrc: No such file or directory
Configuring routing tables to redirect TCP traffic through TOR..
Enable TOR to run on boot..
update-rc.d: using dependency based boot sequencing
update-rc.d: error: cannot find a LSB script for tor

**Comment by jayfajardo** [comment]
looks like there was glitch downloading the TOR package. Did the other packages download fine? Did you have an internet connection going?
